### ISSUE TITLE
JetStream - filtered consumer not unique on workqueue stream - queue consumers

### ISSUE THREAD

**Issue by ovesco** [nats-io/nats.node#461]
I'm hitting a `filtered consumer not unique on workqueue stream` error when trying to setup a WorkQueue policy on a stream with load balanced consumers. I read the documentation a couple times but I guess there's something I don't get.

If I understand correctly, as per [the docs on retention policy](https://docs.nats.io/jetstream/model_deep_dive#stream-limits-retention-and-policy), it is clearly stated that:
```
The WorkQueuePolicy mode is a specialized mode where a message, once consumed and acknowledged, is discarded from the Stream. In this mode, there are a few limits on consumers. Inherently it's about 1 message to one consumer, this means you cannot have overlapping consumers defined on the Stream - needs unique filter subjects.
```

I tried the following options:
```
const natsSubscriptionOpts = consumerOpts();
natsSubscriptionOpts.ackExplicit();
natsSubscriptionOpts.queue('myqueue');
natsSubscriptionOpts.deliverTo('test.sub');
```

According to [this issue response](https://github.com/nats-io/nats.go/issues/712#issuecomment-835410932), you also have to set the durable name (which in my opinion goes against what the documentation says), but I also tried to set it with
```
natsSubscriptionOpts.durable('worker');
```

Anyway I always hit the same error once I try to span more than 1 instance of my consumer service, is there any solution to this? Thanks a lot!

**Edit:** Added some code for example
```js
// Stream creation
jsm.streams.add({
  name: 'ocr-analysis',
  subjects: [
    'ocr.*',
  ],
  retention: RetentionPolicy.Workqueue,
});

// Subscriber creation
const options = natsSubscriptionOpts; // Defined earlier
const subscription = await js.subscribe('ocr.analysis', options);
(async (sub) => {
  for await (const msg of sub) {
    // ...
    msg.ack();
  }
})(subscription);
```

**Comment by danakeydar** [comment]
@derekcollison So it's not possible to implement pull based consumers that consume the same subject in a workqueue retention policy?

**Comment by aricart** [comment]
@danakeydar @derekcollison some clarifications here.

The example is for a push subscription without a queue, you cannot have multiple push consumers on with overlapping interests (filters) that are not part of the same `deliver_group`.

The change that is required here is to make sure the consumers are the same `deliver_group` and the same filter

**Comment by aricart** [comment]
I missed above on your options you are doing a queue, is it possible that there is another consumer that is out of the queue that is defined? List the consumers on the stream.

**Comment by aricart** [comment]
This works for me:
```typescript
  const jsm = await nc.jetstreamManager();
  const stream = nuid.next();
  await jsm.streams.add({
    name: stream,
    subjects: [`${stream}.a`],
    retention: RetentionPolicy.Workqueue,
  });

  const js = nc.jetstream();
  async function consumer(tag: string): Promise<void> {
    const filter = `${stream}.a`;
    const opts = consumerOpts()
        .durable("d")
        .ackExplicit()
        .manualAck()
        .queue("q")
        .deliverTo("s")
        .filterSubject(filter);

    const a = await js.subscribe(filter, opts);
    (async () => {
      for await(const m of a) {
        console.log(`${tag}: ${m.seq}`);
        m.ack()
      }
    })().then()
  }
  
  await consumer("a");
  await consumer("b");
  
  const proms : Promise<PubAck>[] = [];
  for(let i=0; i < 100; i++) {
    proms.push(js.publish(`${stream}.a`))
  }

  await Promise.all((proms));
```

```bash
b: 1
a: 4
b: 2
b: 3
...
```

**Comment by TechInterMezzo** [comment]
So it's not possible to do a work queue with "first come first served" with multiple clients / workers across multiple machines. Or did i misinterpret the "single consumer" statement?

**Comment by AlexanderFillbrunn** [comment]
@TechInterMezzo What tripped me up and maybe you as well is that
> A consumer is a stateful view of a stream. It acts as interface for clients to consume a subset of messages stored in a stream and will keep track of which messages were delivered and acknowledged by clients.
[https://docs.nats.io/nats-concepts/jetstream/consumers]

So for your use case you have *one* consumer, but multiple clients, as they work on the same view.

**Comment by aricart** [comment]
> @TechInterMezzo What tripped me up and maybe you as well is that
> 
> > A consumer is a stateful view of a stream. It acts as interface for clients to consume a subset of messages stored in a stream and will keep track of which messages were delivered and acknowledged by clients.
> > [https://docs.nats.io/nats-concepts/jetstream/consumers]
> 
> So for your use case you have _one_ consumer, but multiple clients, as they work on the same view.

Yes, but they are just multiple processes running as the same consumer.

**Comment by Zeg0** [comment]
You define one consumer, think about the consumer as a pointer on the messages that are inside your workqueue within the jetstream server. 
Multiple applications can subscribe to the same pull consumer (with the same name) and can start working. application 1 and application 2 can fetch/pull messages independently and get a subset of the messages whoever claims them first.  

If you want application 1 and application 2 to get the exact same messages workqueue is propably not what you want. Maybe use an interest stream instead.

**Comment by deadly-panda** [comment]
> WorkQueue policy tends to pair best with pull based consumers, of which you can have as many apps as needed to bind to that and request new messages.
> 
I'm facing the same issue, with multiple pull consumers and WorkQueue policy.
Correct me if I'm wrong, if I have multiple threads each running its own pull subscription and fetching messages on the same subject but different durable names, is the WorkQueue policy going to assure that a message one fetched by one consumer can not be fetched by the other one ? 
If this is not the case, how can I achieve such goal?

**Comment by yousouf9** [comment]
> ```java
> StreamingConnection.subscribe("subject", "queue", msg -> pool.execute(new ProcessMsg(msg)),
>                   new SubscriptionOptions.Builder()
>                       .durableName("durable")
>                       .manualAcks()
>                       .ackWait(Duration.ofSeconds(5))
>                       .maxInFlight(256)
>                       .build());
> ```

please did you find a solution for this?

**Comment by carlosmacapuna** [comment]
> > ```java
> > StreamingConnection.subscribe("subject", "queue", msg -> pool.execute(new ProcessMsg(msg)),
> >                   new SubscriptionOptions.Builder()
> >                       .durableName("durable")
> >                       .manualAcks()
> >                       .ackWait(Duration.ofSeconds(5))
> >                       .maxInFlight(256)
> >                       .build());
> > ```
> 
> please did you find a solution for this?

Hi, yes!

```java
Connection natsConnection = Nats.connectAsynatsConnectionhronously(
    new Options.Builder()
            .server("nats:4222")
            .connectionListener(connectionListener())
            .errorListener(errorListener())
            .maxReconnects(-1)
            .reconnectWait(DurationParser.parse("5s"))
            .connectionTimeout(DurationParser.parse("3s"))
            .pingInterval(DurationParser.parse("30s"))
            .build(),
    true
);
....
....
ConnectionListener connectionListener() {
...
	natsConnection.jetStream().subscribe(
	    "subject.*",
	    "queue",
	    natsConnection.createDispatcher(),
	    this::handleMessage,	//MessageHandler
	    true,			//autoAck
	    PushSubscribeOptions
		    .builder()
		    .configuration(ConsumerConfiguration
		            .builder()
		            .durable("durable")
		            .ackPolicy(AckPolicy.Explicit)
		            .deliverPolicy(DeliverPolicy.All)
		            .build())
		    .stream("stream")
		    .build()
	);
	// flush outgoing communication with/to the server
	natsConnection.flush(Duration.ofSeconds(1));
	...
};
```

**Comment by yousouf9** [comment]
thanks
