### ISSUE TITLE
How to write objecto store entry to file

### ISSUE THREAD

**Issue by dakhnod** [nats-io/nats.node#640]
### Proposed change

I attempted running this code, but it fails with the following error:

```
const natsHandle = await objectBucket.get(`/${path}`);
const writableStream = fs.createWriteStream(path);
await natsHandle.data.pipeTo(writableStream);
```

```
Uncaught TypeError TypeError [ERR_INVALID_ARG_TYPE]: The "transform.writable" property must be an instance of WritableStream. Received an instance of WriteStream
```

My question is:

How do I propertly pipe a nats object contents to a file without loading all the content into ram?

### Use case

Could be useful when downloading data from a nats object store to disk.

**Comment by aricart** [comment]
ObjectStore API is a readable stream - https://nats-io.github.io/nats.deno/types/ObjectResult.html

```
const stream = new ReadableStream(getSomeSource());

for await (const chunk of stream) {
  // Do something with each 'chunk'
}
``
