### ISSUE TITLE
Publishing messages only works some of the time

### ISSUE THREAD

**Issue by MRyanPW** [nats-io/nats.node#642]
### Observed behavior

I'm trying to publish a very basic message to my synadia account and I get maybe one message through every couple of days using the node client, but I can send them consistently through golang.

### Expected behavior

Every message sent ends up in my synadia account or an error message is thrown if there is an issue

### Server and client version

server: whatever synadia is using
windows client:
```
> nats --version
v0.1.4
```
node dependency: `"nats": "^2.28.2",`

### Host environment

Running it locally on windows 11 as well as some amazon boxes

### Steps to reproduce

**package.json:**
```
{
	"dependencies": {
		"nats": "^2.28.2",
		"uuid": "^11.0.3"
	}
}
```

**test.js:**
```
const { connect, credsAuthenticator } = require("nats");
const fs = require('fs');
const path = require('path');
const { v4: uuidv4 } = require('uuid');

const test = async () => {
	const filePath = path.join(__dirname, './~~~synadia~~~.creds');
	const data = fs.readFileSync(filePath, 'utf8');
	const natsConnection = {
		servers: "tls://connect.ngs.global",
		authenticator: credsAuthenticator(new TextEncoder().encode(data)),
	};
	const nc = await connect(natsConnection);
	if (!nc) {
		throw new Error("NATS connection is not established");
	}
	const done = nc.closed();
	
	const transactionId = uuidv4();

	const testEmailToSend = {
			"message": "Never gonna give you up....but, actually I might. We just aren't clicking. I'm sorry, it's over. Find someone else. Or don't, I don't care. You broke my heart, Ethel, I'm not gonna let you do it again!",
			"image_url": "https://media1.tenor.com/m/x8v1oNUOmg4AAAAd/rickroll-roll.gif"
	};
	
	try {
		console.log('sending', emailToSend);
		nc.publish("communications", JSON.stringify(emailToSend));
		console.log("Sent!");
	}
	catch (error) {
		console.error("Failed to send email to: ", error);
	}
}

test();
```

Running `node test.js` shows the console logs but nothing shows up in synadia. However a golang version using the same credentials & connection information & test message shows up just fine

**Comment by aricart** [comment]
I think somehow you are closing/killing the connection before data is sent out.

Try something like;

```javascript
import {connect, delay, createInbox} from "nats"

const c = await connect({servers: "demo.nats.io"});
const inbox = createInbox();
c.subscribe(inbox, {callback: (err, msg) => {
    console.log(msg.json());
}})

const timer = setInterval(async () => {
    // wait as if you are doing something
    await delay(500);
    const start = Date.now();
    const nc = await connect({servers: "demo.nats.io"});
    nc.publish(inbox, JSON.stringify({
        date: new Date().toISOString(),
        message: "hello world doing something",
        payload: new Uint8Array(30)
    }));

    await nc.drain();
    console.log(Date.now() - start, "ms");
}, 2000)

await delay(20000);
clearInterval(timer);
c.close();

```

If you want to be sure you sent something, you can only do so if you send a request:

```javascript
import {connect, delay, createInbox} from "nats"

const c = await connect({servers: "demo.nats.io"});
const inbox = createInbox();
c.subscribe(inbox, {callback: (err, msg) => {
    console.log(msg.json());
    msg.respond();
}});



const timer = setInterval(async () => {
    // wait as if you are doing something
    await delay(500);
    const start = Date.now();
    const nc = await connect({servers: "demo.nats.io"});
    await nc.request(inbox, JSON.stringify({
        date: new Date().toISOString(),
        message: "hello world doing something",
        payload: new Uint8Array(30)
    }));

    await nc.close();
    console.log(Date.now() - start, "ms");
}, 2000)

await delay(20000);
clearInterval(timer);
c.close();
```

**Comment by aricart** [comment]
Also note that:
```javascript
	const nc = await connect(natsConnection);
	if (!nc) {
		throw new Error("NATS connection is not established");
	}
```

Is not really a check - the connect fails, it rejects a promise, which means that nothing will go out, but you should see an error on your side.

**Comment by MRyanPW** [comment]
> I think somehow you are closing/killing the connection before data is sent out.
> 
> Try something like;
> 
> ```js
> import {connect, de~~~
> c.close();
> ```
That's what my assumption as well, and I'd actually added the .drain() call thinking that might do it, but it doesn't seem to actually make it go through.

I put it in a loop, added the delays, and let it run but although I was getting feedback and nothing was throwing errors, the messages never showed up on synadia's side. It (seems to) work fine with demo.nats.io, the subscribe seems to come back with stuff. If I replace the demo.nats.io with the connection information, the subscribe seems to come back as well, however it doesn't appear on the synadia site and the apps we have listening on that subject aren't activated.
